-- SQL Script to insert initial products into public.sri_durga_products

INSERT INTO public.sri_durga_products (id, name, category, price, image, featured, available)
VALUES
  ('bc-vanilla', 'Vanilla Butter Cake', 'butter-cakes', '{"half_kg":150,"one_kg":300}'::jsonb, '/images/products/bc-vanilla.webp', true, true),
  ('bc-strawberry', 'Strawberry Butter Cake', 'butter-cakes', '{"half_kg":150,"one_kg":300}'::jsonb, '/images/products/bc-strawberry.webp', false, true),
  ('bc-pineapple', 'Pineapple Butter Cake', 'butter-cakes', '{"half_kg":150,"one_kg":300}'::jsonb, '/images/products/bc-pineapple.webp', false, true),
  ('bc-butterscotch', 'Butterscotch Butter Cake', 'butter-cakes', '{"half_kg":180,"one_kg":350}'::jsonb, '/images/products/bc-butterscotch.webp', false, true),
  ('bc-chocolate', 'Chocolate Butter Cake', 'butter-cakes', '{"half_kg":180,"one_kg":350}'::jsonb, '/images/products/bc-chocolate.webp', true, true),
  ('bc-greenapple', 'Green Apple Butter Cake', 'butter-cakes', '{"half_kg":150,"one_kg":300}'::jsonb, '/images/products/bc-greenapple.webp', false, true),
  ('pc-vanilla', 'Vanilla Pastry Cake', 'pastry-cakes', '{"half_kg":300,"one_kg":600}'::jsonb, '/images/products/pc-vanilla.webp', false, true),
  ('pc-strawberry', 'Strawberry Pastry Cake', 'pastry-cakes', '{"half_kg":300,"one_kg":600}'::jsonb, '/images/products/pc-strawberry.webp', true, true),
  ('pc-pineapple', 'Pineapple Pastry Cake', 'pastry-cakes', '{"half_kg":300,"one_kg":600}'::jsonb, '/images/products/pc-pineapple.webp', true, true),
  ('pc-butterscotch', 'Butterscotch Pastry Cake', 'pastry-cakes', '{"half_kg":350,"one_kg":700}'::jsonb, '/images/products/pc-butterscotch.webp', false, true),
  ('pc-chocolate', 'Chocolate Pastry Cake', 'pastry-cakes', '{"half_kg":350,"one_kg":700}'::jsonb, '/images/products/pc-chocolate.webp', false, true),
  ('pc-greenapple', 'Green Apple Pastry Cake', 'pastry-cakes', '{"half_kg":300,"one_kg":600}'::jsonb, '/images/products/pc-greenapple.webp', false, true),
  ('pc-redvelvet', 'Red Velvet Pastry Cake', 'pastry-cakes', '{"half_kg":400,"one_kg":800}'::jsonb, '/images/products/pc-redvelvet.webp', false, true),
  ('pc-blackforest', 'Black Forest Pastry Cake', 'pastry-cakes', '{"half_kg":400,"one_kg":800}'::jsonb, '/images/products/pc-blackforest.webp', false, true),
  ('pc-honeyalmond', 'Honey Almond Pastry Cake', 'pastry-cakes', '{"half_kg":400,"one_kg":800}'::jsonb, '/images/products/pc-honeyalmond.webp', false, true),
  ('sw-kova', 'Kova Items', 'sweets', '{"quarter_kg":100,"half_kg":200,"one_kg":400}'::jsonb, '/images/products/sw-kova.webp', true, true),
  ('sw-kalakandha', 'Kalakandha', 'sweets', '{"quarter_kg":120,"half_kg":220,"one_kg":440}'::jsonb, '/images/products/sw-kalakandha.webp', true, true),
  ('sw-mysorepak', 'Ghee Mysorepak', 'sweets', '{"quarter_kg":120,"half_kg":220,"one_kg":440}'::jsonb, '/images/products/sw-mysorepak.webp', true, true),
  ('sw-icecreamburfi', 'Ice cream burfi', 'sweets', '{"quarter_kg":120,"half_kg":220,"one_kg":440}'::jsonb, '/images/products/sw-icecreamburfi.webp', false, true),
  ('sw-sunnonda', 'Sunnonda', 'sweets', '{"quarter_kg":100,"half_kg":200,"one_kg":400}'::jsonb, '/images/products/sw-sunnonda.webp', false, true),
  ('sw-besaraladdu', 'Besara laddu', 'sweets', '{"quarter_kg":90,"half_kg":180,"one_kg":360}'::jsonb, '/images/products/sw-besaraladdu.webp', false, true),
  ('sw-thokkuduladdu', 'Thokkudu laddu', 'sweets', '{"quarter_kg":60,"half_kg":120,"one_kg":240}'::jsonb, '/images/products/sw-thokkuduladdu.webp', false, true),
  ('sw-mothichurladdu', 'Mothi chur laddu', 'sweets', '{"quarter_kg":70,"half_kg":140,"one_kg":280}'::jsonb, '/images/products/sw-mothichurladdu.webp', true, true),
  ('sw-laddu', 'Laddu', 'sweets', '{"quarter_kg":60,"half_kg":120,"one_kg":240}'::jsonb, '/images/products/sw-laddu.webp', false, true),
  ('sw-kaja', 'Kaja', 'sweets', '{"quarter_kg":60,"half_kg":120,"one_kg":240}'::jsonb, '/images/products/sw-kaja.webp', false, true),
  ('sw-jangiri', 'Jangiri', 'sweets', '{"quarter_kg":60,"half_kg":120,"one_kg":240}'::jsonb, '/images/products/sw-jangiri.webp', false, true),
  ('br-milk', 'Milk Bread', 'breads', '{"unit":50}'::jsonb, '/images/products/br-milk.webp', true, true),
  ('br-brown', 'Brown Bread', 'breads', '{"unit":70}'::jsonb, '/images/products/br-brown.webp', true, true),
  ('br-wheat', 'Wheat Bread', 'breads', '{"unit":60}'::jsonb, '/images/products/br-wheat.webp', false, true),
  ('pf-veg', 'Veg Puff', 'puffs', '{"unit":20}'::jsonb, '/images/products/pf-veg.webp', true, true),
  ('pf-egg', 'Egg Puff', 'puffs', '{"unit":25}'::jsonb, '/images/products/pf-egg.webp', false, true),
  ('pf-chicken', 'Chicken Puff', 'puffs', '{"unit":35}'::jsonb, '/images/products/pf-chicken.webp', true, true);
